homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('daftar/', views.daftar, name='daftar'),
    path('masuk/', views.masuk, name='masuk'),
    path('keluar/', views.keluar, name='keluar'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'index.html')

def masuk(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'masuk.html', {'response':'Username/Password Salah :('})
    return render(request, 'masuk.html')

def keluar(request):
    request.session.flush()
    logout(request)
    return redirect('/')

def daftar(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/masuk/')
    return render(request, 'daftar.html', {'form' : form})

homepage/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">
  </head>
  <body>
      {% block content %}
      <!--Isi Page-->
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
    crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/daftar.html
{% include 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Register</title>
</head>
<body>
    {% block content %}
    <h1 class="sapa">Tak Kenal Maka Tak Sayang, Yuk Isi!</h1>
    <div class="container">
        <div class="row">
            <form method="post">
                {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                </tr>
             </table>
             <a href="{% url 'homepage:masuk' %}">
                <button class="btn btn-success" id="setuju">Daftarkan!</button>
            </a>
        </div>
    </div>
    {% if form.errors %}
    <h5 style="text-align: center;">Coba lagi :(</h5>
    {% endif %}
    {% endblock %}
</body>
</html>

homepage/templates/index.html
{% include 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Story 10</title>
</head>
<body>
    {% block content %}
    {% if user.is_authenticated %}
    <div class="sapa">
        <h1>Selamat Datang, {{ user.username }}!</h1>
        <h1>Kita Telah Berteman :D Berbahagialah!</h1>
    </div>
    <div class="sapa">
        <h6>Jikalau sibuk, silakan keluar~</h6>
    <a href="{% url 'homepage:keluar' %}">
        <button type="button" class="btn btn-dark" id="logout">Logout</button>
    </a>
    </div>

    {% else %}
    <h1 class="sapa">Selamat Datang, Calon Teman!</h1>
    <div class="sapa">
        <h3>Silakan daftar jika ingin berteman, hehe :D</h3>
        <a href="{% url 'homepage:daftar' %}">
            <button type="submit" class="btn btn-primary" id="daftar">Daftar!</button>
        </a>
    </div>
    <div class="sapa">
        <h3>Kita sudah berteman? Login saja :D</h3>
        <a href="{% url 'homepage:masuk' %}">
            <button type="submit" class="btn btn-success" id="login">Login!</button>
        </a>
    </div>
    {% endif %}
    {% endblock %}
</body>
</html>

homepage/templates/masuk.html
{% include 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Login</title>
</head>
<body>
    {% block content %}
    <h2 class="sapa">Login dulu ya :)</h2>
    <form action="" method="post" class="d-flex flex-column justify-content-center">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="username" id="username" autocomplete="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" autocomplete="password">
        </div>
        <h6>{{response}}</h6>
        <button type="submit" class="btn btn-success" id="login">Login!</button>
        <p>Kita belum berteman? <a href="{% url 'homepage:daftar' %}" id="daftar">Daftar</a> dulu ya</p>
    </form>

    {% endblock %}
</form>
</body>
</html>